# Jekyll configuration for GitHub Pages
title: Yara Sleiman - Academic Website
description: Political Science Researcher
baseurl: ""
url: "https://yarasleiman.github.io"

# Disable Jekyll processing for certain files
exclude:
  - README.md
  - LICENSE.md
  - .gitignore
  - .github/
  - content/
  - config/
  - layouts/
  - static/
  - assets/
  - data/
  - images/
  - theme.toml
  - academic.Rproj
  - netlify.toml
  - preview.png
  - go.mod
  - .editorconfig
  - .hugo_build.lock
  - hugo.tar.gz

# Include only the files we want to serve
include:
  - index.html
  - CNAME
